### ISSUE TITLE
Horizontal results responsive layout when scrollbar is disabled

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#151]
The horizontal layout should be responsive when the scrollbar is disabled. Reference custom CSS:

```css
.asp_r .item .asp_image {
    width: 100% !important;
    height: auto !important;
}

.asp_r .item .asp_image img {
    display: block;
}

@media only screen and (max-width: 768px) {
    .asp_r .item {
        width: 42% !important;
    }
}

@media only screen and (max-width: 480px) {
    .asp_r .item {
        width: 90% !important;
    }
}
```

**Comment by ernestmarcinko** [comment]
```css
.asp_r .item .asp_image {
    width: 100% !important;
    height: auto !important;
}

.asp_r .item .asp_image img {
    display: block;
}

.asp_r {
    margin-left: -10px !important;
    margin-right: -10px !important;
}

.asp_r .item {
    flex: 0 0 calc(33.3% - 40px);
    margin: 10px !important;
    padding: 10px !important;
}
```
