### ISSUE TITLE
Salient and other themes tend to override the color picker button visibility

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#190]
Unfortunately some themes still like to load up all their assets on the whole back-end. Even worse, most of their JS and CSS is not properly scoped to the theme related selectors, so they just override things randomly. This is the second time seeing two different themes overriding the buttons on the color picker, so a proper CSS override is the only option:

```css
.asp-backend .sp-button-container.sp-cf {
	display: block !important;
	opacity: 1 !important;
	visibility: visible !important;
}
```

This will not affect any other theme nor plugin scope. Moreover Ajax Search Pro asset files are only loaded on Ajax Search Pro back-end pages. I strognly recommend other developers following this rule.
