### ISSUE TITLE
Show a message when Product is selected, that Hidden & Catalog are not excluded

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#78]
When selecting the Product post type the plugin should display an information box informing the user that Hidden WooCommerce products are not excluded, with possibly a link to the knowledge base explaining how to do it.˛

## Example

![image](https://github.com/WPDreams/ajax-search-pro-development/assets/6159897/ff7d6584-dbcb-46a3-8dcb-de559c29b73f)

## CSS

```css
.wdo_box-warning {
    padding: 2em;
    background: #f9f9f9;
    border-radius: 6px;
    border: 1px solid #dbdbdb;
    border-left: 6px solid #d81a1a;
    color: #161616;
}
```
